version: '2'
services:
    php:
        build: ./docker/php-fpm72
        environment:
            HOST_IP: 10.15.10.89
        volumes:
            - ./:/var/www/manriBot
            - ~/.ssh:/home/wwwagent/.ssh
    nginx:
        build: ./docker/nginx
        ports:
            - "8443:443"
        links:
            - php
        volumes_from:
            - php
    manriBot:
        image: abh1nav/dockerui
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - nginx
